baseURL = "https://chartmuseum.com"
publishdir = "app"
languageCode = "en-us"
languageLang = "en"
title = "ChartMuseum - Helm Chart Repository"

[params]
repo = "https://github.com/helm/chartmuseum"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
