[build]
  command = "make build"
  publish = "app"

[build.environment]
  HUGO_VERSION = "0.81.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "make build-preview"

[context.branch-deploy]
  command = "make build-preview"

